spring:
datasource: 
 url: ${MYSQL_CI_URL}
 username: ${MYSQL_USER}
 password: ${MYSQL_PASSWORD}
jpa:
   hibernate:
     ddl-auto: update
     show-sql: true
server:
 port: 8084

# server.port=8082
# spring.datasource.url=jdbc:mysql://localhost:3306/moviecruiser
# spring.datasource.username=root
# spring.datasource.password=root
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
#   